### ISSUE TITLE
Ignored When Double Tap on Touchpad

### ISSUE THREAD

**Issue by AyuMatahari** [nenning/DoubleClickFix#5]
The program ignores the double tap on the touchpad because it thinks the tap delay is 0 ms. I tried lowering the minimum speed down to 1, but it still ignores the tap.

![DoubleClickFix_2024-08-12 105229243](https://github.com/user-attachments/assets/6288e445-d5f8-42c0-93af-4976e631717f)

**Comment by nenning** [comment]
Thanks for the report. I released a workaround. I hope it helps. But I wasn't able to find a clean solution. I might have a closer look at the issue in the future.
At the moment, you get a new checkbox in the UI. When checked, the tool will allow double clicks of 0ms duration. But my broken mouse for example also sends these sometimes, so some accidental double-clicks might slip through...

**Comment by nenning** [comment]
Release 1.0.2.0 should have even better support. The checkbox mentioned above should not be needed anymore.
You should see a log "switched to device 0" when you used the touchscreen or touchpad and all double-clicks should be allowed.
If this is not working, any feedback is welcome!
