### ISSUE TITLE
Feature request - Add more buttons to support Logitech 502 mouse.

### ISSUE THREAD

**Issue by akzzy** [nenning/DoubleClickFix#8]
Doubleclickfix works with the 5 buttons that already have. but i have issues with my DPI button which is not available in doubleclickfix.
Can you add support for additional buttons.
I can help you with the testing if want.

**Comment by nenning** [comment]
I don't think there's a way to do this with the mechanism I use. I'm already handling all the buttons provided by Windows.
See https://learn.microsoft.com/en-us/windows/win32/winmsg/lowlevelmouseproc
DPI and other special buttons might even be manufacturer-specific.

**Comment by arcadepro** [comment]
As a solution for this user he could perhaps use Logitech's new 'Onboard Memory Manager' software and program these additional keys to send 'keyboard' presses. (Like PageUp, Home etc.). 

I assume if he then adjusts his key repeat rate in Windows it may help a little. It wont help if he's using the 'dpi up/down' assignments though.
