### ISSUE TITLE
How to change Icon ?

### ISSUE THREAD

**Issue by keo950** [nenning/DoubleClickFix#9]
Hey, this app is working perfectly but i just wanted to know how i do to change the application icon ? thank in advance
![image_2024-12-16_222653962](https://github.com/user-attachments/assets/98e6a250-edc7-4360-a970-a46c968f0f5d)

**Comment by keo950** [comment]
And also if changing the icon is too hard how can i hide the icon from the system Tray ?

**Comment by nenning** [comment]
Changing the icon is not supported. You can go to the windows taskbar settings -> other system tray icons -> DoubleClickFix and switch the slider to "Off" to hide the icon
